/**
 * Каталог автозапчастей Владивосток (без стоимости).
 * Источник: Каталог Автозапчастей Владивосток.pdf
 * Для поиска и выбора запчастей под заказ.
 */
const CATALOG_DATA = [
  // 1. Двигатели и компоненты двигателя
  { id: "d01", name: "ДВС контрактный Toyota 1JZ-GTE, 2JZ-GTE (Mark II, Supra, Aristo, Crown)", category: "Двигатель и навесное", subcategory: "Контрактные двигатели", make: "Toyota", model: "Mark II, Supra, Aristo, Crown", keywords: "двигатель мотор 1jz 2jz" },
  { id: "d02", name: "ДВС контрактный Toyota 3S-GE, 4A-GE, 1UZ-FE", category: "Двигатель и навесное", subcategory: "Контрактные двигатели", make: "Toyota", model: "", keywords: "двигатель мотор 3s 4a 1uz" },
  { id: "d03", name: "ДВС контрактный Nissan RB20DET, RB25DET (Skyline, Laurel)", category: "Двигатель и навесное", subcategory: "Контрактные двигатели", make: "Nissan", model: "Skyline, Laurel", keywords: "двигатель мотор rb20 rb25" },
  { id: "d04", name: "ДВС контрактный Nissan SR20DET, VQ35DE (Silvia, Cefiro)", category: "Двигатель и навесное", subcategory: "Контрактные двигатели", make: "Nissan", model: "Silvia, Cefiro", keywords: "двигатель мотор sr20 vq35" },
  { id: "d05", name: "ДВС контрактный Honda B16A, B18C, K20A, F20C (Civic, Integra, S2000)", category: "Двигатель и навесное", subcategory: "Контрактные двигатели", make: "Honda", model: "Civic, Integra, S2000", keywords: "двигатель мотор b16 k20" },
  { id: "d06", name: "ДВС контрактный Mazda 13B-REW, BP-ZE, FE3N (RX-7, Familia, Capella)", category: "Двигатель и навесное", subcategory: "Контрактные двигатели", make: "Mazda", model: "RX-7, Familia, Capella", keywords: "двигатель мотор 13b" },
  { id: "d07", name: "ДВС контрактный Subaru EJ20, EJ25, EJ207 (Impreza, Legacy, Forester)", category: "Двигатель и навесное", subcategory: "Контрактные двигатели", make: "Subaru", model: "Impreza, Legacy, Forester", keywords: "двигатель мотор ej20 ej25" },
  { id: "d08", name: "ДВС контрактный Mitsubishi 4G63, 6A13, 6G72 (Lancer Evolution, Galant)", category: "Двигатель и навесное", subcategory: "Контрактные двигатели", make: "Mitsubishi", model: "Lancer Evolution, Galant", keywords: "двигатель мотор 4g63" },
  { id: "d09", name: "ГБЦ для Toyota (3S-FE, 5S-FE, 1JZ, 2JZ)", category: "Двигатель и навесное", subcategory: "Головки блока цилиндров", make: "Toyota", model: "", keywords: "гбц головка 3s 5s 1jz 2jz" },
  { id: "d10", name: "ГБЦ для Nissan (SR20, RB25, VQ35)", category: "Двигатель и навесное", subcategory: "Головки блока цилиндров", make: "Nissan", model: "", keywords: "гбц головка sr20 rb25 vq35" },
  { id: "d11", name: "ГБЦ для Honda (B-series, K-series)", category: "Двигатель и навесное", subcategory: "Головки блока цилиндров", make: "Honda", model: "", keywords: "гбц головка b-series k-series" },
  { id: "d12", name: "ГБЦ для Subaru (EJ20, EJ25)", category: "Двигатель и навесное", subcategory: "Головки блока цилиндров", make: "Subaru", model: "", keywords: "гбц головка ej20 ej25" },
  { id: "d13", name: "ГБЦ с распредвалами, клапанами, крышкой", category: "Двигатель и навесное", subcategory: "Головки блока цилиндров", make: "", model: "", keywords: "гбц распредвал клапаны" },
  { id: "d14", name: "Блок цилиндров рядный 4-цилиндровый", category: "Двигатель и навесное", subcategory: "Блоки цилиндров", make: "", model: "", keywords: "блок цилиндров рядный" },
  { id: "d15", name: "Блок цилиндров рядный 6-цилиндровый (1JZ, 2JZ, RB)", category: "Двигатель и навесное", subcategory: "Блоки цилиндров", make: "", model: "", keywords: "блок цилиндров 1jz 2jz rb" },
  { id: "d16", name: "Блок цилиндров V-образный (VQ, 1UZ, 3UZ)", category: "Двигатель и навесное", subcategory: "Блоки цилиндров", make: "", model: "", keywords: "блок цилиндров vq 1uz 3uz" },
  { id: "d17", name: "Поршни оригинальные", category: "Двигатель и навесное", subcategory: "Поршневая группа", make: "", model: "", keywords: "поршень" },
  { id: "d18", name: "Поршневые кольца, пальцы, шатуны", category: "Двигатель и навесное", subcategory: "Поршневая группа", make: "", model: "", keywords: "поршневые кольца шатуны вкладыши" },
  { id: "d19", name: "Вкладыши коленвала и шатунные", category: "Двигатель и навесное", subcategory: "Поршневая группа", make: "", model: "", keywords: "вкладыши коленвал" },
  { id: "d20", name: "Коленвал (стандартный, усиленный)", category: "Двигатель и навесное", subcategory: "Коленвал и распредвал", make: "", model: "", keywords: "коленвал" },
  { id: "d21", name: "Распредвал (стандартный, спортивный)", category: "Двигатель и навесное", subcategory: "Коленвал и распредвал", make: "", model: "", keywords: "распредвал" },
  { id: "d22", name: "Шкив коленвала, демпфер крутильных колебаний", category: "Двигатель и навесное", subcategory: "Коленвал и распредвал", make: "", model: "", keywords: "шкив демпфер коленвал" },
  { id: "d23", name: "Турбина IHI (CT9A, CT12A, CT15B, CT26)", category: "Двигатель и навесное", subcategory: "Турбины и компрессоры", make: "", model: "", keywords: "турбина ihi ct9 ct12 ct26" },
  { id: "d24", name: "Турбина Garrett", category: "Двигатель и навесное", subcategory: "Турбины и компрессоры", make: "", model: "", keywords: "турбина garrett" },
  { id: "d25", name: "Интеркулер, патрубки турбины, актуатор", category: "Двигатель и навесное", subcategory: "Турбины и компрессоры", make: "", model: "", keywords: "интеркулер актуатор турбина" },
  { id: "d26", name: "Впускной коллектор, выпускной коллектор (Headers)", category: "Двигатель и навесное", subcategory: "Впуск и выпуск", make: "", model: "", keywords: "коллектор впуск выпуск headers" },
  { id: "d27", name: "Дроссельная заслонка, резонатор впуска", category: "Двигатель и навесное", subcategory: "Впуск и выпуск", make: "", model: "", keywords: "дроссель резонатор" },
  { id: "d28", name: "Глушитель передний, задний; катализатор; downpipe", category: "Двигатель и навесное", subcategory: "Впуск и выпуск", make: "", model: "", keywords: "глушитель катализатор downpipe" },
  { id: "d29", name: "Радиатор охлаждения двигателя", category: "Двигатель и навесное", subcategory: "Охлаждение и смазка", make: "", model: "", keywords: "радиатор охлаждение" },
  { id: "d30", name: "Радиатор АКПП, вентилятор охлаждения", category: "Двигатель и навесное", subcategory: "Охлаждение и смазка", make: "", model: "", keywords: "радиатор акпп вентилятор" },
  { id: "d31", name: "Помпа водяная, термостат", category: "Двигатель и навесное", subcategory: "Охлаждение и смазка", make: "", model: "", keywords: "помпа термостат" },
  { id: "d32", name: "Масляный насос, масляный радиатор, патрубки охлаждения", category: "Двигатель и навесное", subcategory: "Охлаждение и смазка", make: "", model: "", keywords: "масло насос радиатор" },
  { id: "d33", name: "Генератор (80A, 100A, 120A, 150A)", category: "Двигатель и навесное", subcategory: "Генераторы и стартеры", make: "", model: "", keywords: "генератор" },
  { id: "d34", name: "Стартер", category: "Двигатель и навесное", subcategory: "Генераторы и стартеры", make: "", model: "", keywords: "стартер" },
  // 2. Трансмиссия
  { id: "t01", name: "АКПП Toyota A340E, A340H, A541E, U140E, U151E", category: "Трансмиссия", subcategory: "АКПП", make: "Toyota", model: "", keywords: "акпп автомат a340 u140" },
  { id: "t02", name: "АКПП Nissan RE4F04A, RE4F04B, RE5R05A", category: "Трансмиссия", subcategory: "АКПП", make: "Nissan", model: "", keywords: "акпп автомат re4 re5" },
  { id: "t03", name: "АКПП Honda M4TA, MDKA, MCJA, SLXA", category: "Трансмиссия", subcategory: "АКПП", make: "Honda", model: "", keywords: "акпп автомат m4ta" },
  { id: "t04", name: "АКПП Mazda FN4A-EL, GF4A-EL", category: "Трансмиссия", subcategory: "АКПП", make: "Mazda", model: "", keywords: "акпп автомат fn4a gf4a" },
  { id: "t05", name: "АКПП Subaru 4EAT, 5EAT", category: "Трансмиссия", subcategory: "АКПП", make: "Subaru", model: "", keywords: "акпп автомат 4eat 5eat" },
  { id: "t06", name: "АКПП Mitsubishi F4A41, F4A42, F5A51", category: "Трансмиссия", subcategory: "АКПП", make: "Mitsubishi", model: "", keywords: "акпп автомат f4a f5a" },
  { id: "t07", name: "АКПП в сборе с гидротрансформатором, радиатором, селектором", category: "Трансмиссия", subcategory: "АКПП", make: "", model: "", keywords: "акпп гидротрансформатор селектор" },
  { id: "t08", name: "МКПП Toyota S53, W55, W58, R154, E153", category: "Трансмиссия", subcategory: "МКПП", make: "Toyota", model: "", keywords: "мкпп механика w55 r154" },
  { id: "t09", name: "МКПП Nissan FS5W71, FS5R30A, FS5R90A", category: "Трансмиссия", subcategory: "МКПП", make: "Nissan", model: "", keywords: "мкпп механика fs5" },
  { id: "t10", name: "МКПП Honda S80, S4C, Y80", category: "Трансмиссия", subcategory: "МКПП", make: "Honda", model: "", keywords: "мкпп механика s80 y80" },
  { id: "t11", name: "МКПП Mazda RS5F31A, R15M-D", category: "Трансмиссия", subcategory: "МКПП", make: "Mazda", model: "", keywords: "мкпп механика rs5f" },
  { id: "t12", name: "МКПП Subaru TY75, TY85, TY856", category: "Трансмиссия", subcategory: "МКПП", make: "Subaru", model: "", keywords: "мкпп механика ty75 ty85" },
  { id: "t13", name: "Вариатор Nissan RE0F06A, RE0F10A, RE0F11A", category: "Трансмиссия", subcategory: "Вариатор CVT", make: "Nissan", model: "", keywords: "вариатор cvt re0f" },
  { id: "t14", name: "Вариатор Subaru TR580, TR690", category: "Трансмиссия", subcategory: "Вариатор CVT", make: "Subaru", model: "", keywords: "вариатор cvt tr580" },
  { id: "t15", name: "Вариатор Toyota K111, K112, K310", category: "Трансмиссия", subcategory: "Вариатор CVT", make: "Toyota", model: "", keywords: "вариатор cvt k111 k310" },
  { id: "t16", name: "Сцепление (корзина, диск, выжимной подшипник)", category: "Трансмиссия", subcategory: "Компоненты", make: "", model: "", keywords: "сцепление корзина диск" },
  { id: "t17", name: "Маховик, гидротрансформатор", category: "Трансмиссия", subcategory: "Компоненты", make: "", model: "", keywords: "маховик гидротрансформатор" },
  { id: "t18", name: "Валы КПП (первичный, вторичный), синхронизаторы", category: "Трансмиссия", subcategory: "Компоненты", make: "", model: "", keywords: "вал кпп синхронизатор" },
  { id: "t19", name: "Селектор КПП, кулиса переключения", category: "Трансмиссия", subcategory: "Компоненты", make: "", model: "", keywords: "селектор кулиса" },
  { id: "t20", name: "Раздаточная коробка", category: "Трансмиссия", subcategory: "Раздатка и кардан", make: "", model: "", keywords: "раздатка раздаточная" },
  { id: "t21", name: "Карданный вал (передний, задний), крестовины", category: "Трансмиссия", subcategory: "Раздатка и кардан", make: "", model: "", keywords: "кардан крестовина" },
  { id: "t22", name: "ШРУС внутренний, наружный; пыльники; приводной вал", category: "Трансмиссия", subcategory: "Раздатка и кардан", make: "", model: "", keywords: "шрус граната привод пыльник" },
  // 3. Ходовая часть и подвеска
  { id: "h01", name: "Стойка передняя в сборе с пружиной", category: "Ходовая/подвеска", subcategory: "Амортизаторы и стойки", make: "", model: "", keywords: "стойка передняя амортизатор" },
  { id: "h02", name: "Стойка задняя, амортизатор задний", category: "Ходовая/подвеска", subcategory: "Амортизаторы и стойки", make: "", model: "", keywords: "стойка задняя амортизатор" },
  { id: "h03", name: "Газомасляный амортизатор, пневмостойка", category: "Ходовая/подвеска", subcategory: "Амортизаторы и стойки", make: "", model: "", keywords: "пневмостойка газомасляный" },
  { id: "h04", name: "Амортизаторы KYB, Tokico, Showa", category: "Ходовая/подвеска", subcategory: "Амортизаторы и стойки", make: "", model: "", keywords: "kyb tokico showa" },
  { id: "h05", name: "Пружина передняя, задняя; рессора; усиленные пружины", category: "Ходовая/подвеска", subcategory: "Пружины", make: "", model: "", keywords: "пружина рессора" },
  { id: "h06", name: "Рычаг передней подвески (верхний, нижний)", category: "Ходовая/подвеска", subcategory: "Рычаги", make: "", model: "", keywords: "рычаг передний подвеска" },
  { id: "h07", name: "Рычаг задней подвески, сайлентблоки, шаровая опора", category: "Ходовая/подвеска", subcategory: "Рычаги", make: "", model: "", keywords: "рычаг задний сайлентблок шаровая" },
  { id: "h08", name: "Стабилизатор поперечной устойчивости (передний, задний)", category: "Ходовая/подвеска", subcategory: "Стабилизаторы", make: "", model: "", keywords: "стабилизатор стойка стабилизатора" },
  { id: "h09", name: "Втулка стабилизатора, стойка стабилизатора", category: "Ходовая/подвеска", subcategory: "Стабилизаторы", make: "", model: "", keywords: "втулка стабилизатора" },
  { id: "h10", name: "Подшипник ступицы передний, задний; ступица в сборе", category: "Ходовая/подвеска", subcategory: "Ступицы", make: "", model: "", keywords: "ступица подшипник ступицы" },
  { id: "h11", name: "Ступичный узел с датчиком ABS", category: "Ходовая/подвеска", subcategory: "Ступицы", make: "", model: "", keywords: "ступица абс" },
  // 4. Рулевое управление
  { id: "r01", name: "Рулевая рейка с ЭУР (EPS)", category: "Рулевое", subcategory: "Рейки", make: "", model: "", keywords: "рейка рулевая эур eps" },
  { id: "r02", name: "Рулевая рейка с ГУР", category: "Рулевое", subcategory: "Рейки", make: "", model: "", keywords: "рейка рулевая гур" },
  { id: "r03", name: "Рулевой редуктор (внедорожники)", category: "Рулевое", subcategory: "Рейки", make: "", model: "", keywords: "редуктор рулевой" },
  { id: "r04", name: "Насос ГУР (Toyota, Nissan, Honda, Mazda)", category: "Рулевое", subcategory: "Насосы ГУР", make: "", model: "", keywords: "насос гур" },
  { id: "r05", name: "Бачок ГУР, шланги высокого давления ГУР", category: "Рулевое", subcategory: "Насосы ГУР", make: "", model: "", keywords: "бачок гур шланг" },
  { id: "r06", name: "Рулевая тяга (левая, правая), наконечник тяги", category: "Рулевое", subcategory: "Тяги и наконечники", make: "", model: "", keywords: "тяга наконечник рулевой" },
  { id: "r07", name: "Рулевая сошка, продольная тяга", category: "Рулевое", subcategory: "Тяги и наконечники", make: "", model: "", keywords: "сошка рулевая" },
  { id: "r08", name: "Рулевая колонка в сборе, рулевой вал", category: "Рулевое", subcategory: "Колонка и руль", make: "", model: "", keywords: "колонка рулевая вал руль" },
  { id: "r09", name: "Руль (штатный, спортивный), подрулевые переключатели", category: "Рулевое", subcategory: "Колонка и руль", make: "", model: "", keywords: "руль переключатель" },
  // 5. Тормозная система
  { id: "b01", name: "Суппорт передний, задний", category: "Тормоза", subcategory: "Суппорты", make: "", model: "", keywords: "суппорт тормозной калипер" },
  { id: "b02", name: "Ремкомплект суппорта, скоба суппорта", category: "Тормоза", subcategory: "Суппорты", make: "", model: "", keywords: "ремкомплект суппорт" },
  { id: "b03", name: "Суппорт Brembo (спортивный)", category: "Тормоза", subcategory: "Суппорты", make: "", model: "", keywords: "brembo суппорт" },
  { id: "b04", name: "Тормозной диск передний (вентилируемый), задний", category: "Тормоза", subcategory: "Диски и барабаны", make: "", model: "", keywords: "тормозной диск" },
  { id: "b05", name: "Тормозной барабан, диск перфорированный", category: "Тормоза", subcategory: "Диски и барабаны", make: "", model: "", keywords: "барабан диск тормоз" },
  { id: "b06", name: "Главный тормозной цилиндр (ГТЦ)", category: "Тормоза", subcategory: "ГТЦ и усилитель", make: "", model: "", keywords: "гтц главный цилиндр" },
  { id: "b07", name: "Вакуумный усилитель тормозов, бачок тормозной жидкости", category: "Тормоза", subcategory: "ГТЦ и усилитель", make: "", model: "", keywords: "вакуумник усилитель тормоз" },
  { id: "b08", name: "Блок ABS, датчик ABS", category: "Тормоза", subcategory: "ABS", make: "", model: "", keywords: "абс блок датчик" },
  { id: "b09", name: "Блок VSC/VDC/ESP, гидроблок ABS, насос ABS", category: "Тормоза", subcategory: "ABS", make: "", model: "", keywords: "vsc esp гидроблок абс" },
  // 6. Электрооборудование
  { id: "e01", name: "Генератор 80A, 100A, 120A, 150A", category: "Электрика/ЭБУ", subcategory: "Генераторы и стартеры", make: "", model: "", keywords: "генератор" },
  { id: "e02", name: "Стартер, реле-регулятор, бендикс, щеточный узел", category: "Электрика/ЭБУ", subcategory: "Генераторы и стартеры", make: "", model: "", keywords: "стартер реле бендикс" },
  { id: "e03", name: "ЭБУ двигателя (Engine ECU)", category: "Электрика/ЭБУ", subcategory: "ЭБУ", make: "", model: "", keywords: "эбу двигатель ecu" },
  { id: "e04", name: "ЭБУ АКПП, ЭБУ ABS, ЭБУ подушек безопасности", category: "Электрика/ЭБУ", subcategory: "ЭБУ", make: "", model: "", keywords: "эбу акпп абс airbag" },
  { id: "e05", name: "ЭБУ климат-контроля, ЭБУ навигации и мультимедиа", category: "Электрика/ЭБУ", subcategory: "ЭБУ", make: "", model: "", keywords: "эбу климат навигация" },
  { id: "e06", name: "Датчик положения коленвала, распредвала; ДМРВ; MAP", category: "Электрика/ЭБУ", subcategory: "Датчики", make: "", model: "", keywords: "датчик коленвал распредвал дмрв" },
  { id: "e07", name: "Лямбда-зонд, датчик детонации, температуры, давления масла", category: "Электрика/ЭБУ", subcategory: "Датчики", make: "", model: "", keywords: "лямбда датчик кислорода детонация" },
  { id: "e08", name: "Датчик скорости (VSS)", category: "Электрика/ЭБУ", subcategory: "Датчики", make: "", model: "", keywords: "датчик скорости vss" },
  { id: "e09", name: "Катушка зажигания, модуль зажигания", category: "Электрика/ЭБУ", subcategory: "Зажигание", make: "", model: "", keywords: "катушка зажигания" },
  { id: "e10", name: "Высоковольтные провода, свечи зажигания (NGK, Denso), трамблер", category: "Электрика/ЭБУ", subcategory: "Зажигание", make: "", model: "", keywords: "свечи провода трамблер" },
  { id: "e11", name: "Проводка двигателя, салона, дверей; жгуты; разъемы; реле", category: "Электрика/ЭБУ", subcategory: "Проводка", make: "", model: "", keywords: "проводка жгут разъем реле" },
  { id: "e12", name: "Аккумулятор 55Ah, 65Ah, 75Ah; для гибрида; клеммы", category: "Электрика/ЭБУ", subcategory: "Аккумуляторы", make: "", model: "", keywords: "аккумулятор батарея" },
  // 7. Кузовные детали
  { id: "k01", name: "Капот, дверь передняя (левая, правая), задняя", category: "Кузов", subcategory: "Внешние элементы", make: "", model: "", keywords: "капот дверь" },
  { id: "k02", name: "Крышка багажника, пятая дверь", category: "Кузов", subcategory: "Внешние элементы", make: "", model: "", keywords: "багажник крышка пятая дверь" },
  { id: "k03", name: "Крыло переднее (левое, правое), заднее", category: "Кузов", subcategory: "Внешние элементы", make: "", model: "", keywords: "крыло" },
  { id: "k04", name: "Бампер передний, задний", category: "Кузов", subcategory: "Внешние элементы", make: "", model: "", keywords: "бампер" },
  { id: "k05", name: "Лобовое стекло, боковое, заднее; стекло двери", category: "Кузов", subcategory: "Остекление", make: "", model: "", keywords: "стекло лобовое" },
  { id: "k06", name: "Стеклоподъемник (электрический, механический), мотор стеклоподъемника", category: "Кузов", subcategory: "Остекление", make: "", model: "", keywords: "стеклоподъемник" },
  { id: "k07", name: "Фара передняя (левая, правая), фонарь задний", category: "Оптика", subcategory: "Фары и фонари", make: "", model: "", keywords: "фара фонарь" },
  { id: "k08", name: "ПТФ, повторитель поворота, стоп-сигнал; ксенон; LED-модуль", category: "Оптика", subcategory: "Фары и фонари", make: "", model: "", keywords: "птф ксенон led" },
  { id: "k09", name: "Зеркало боковое (левое, правое), с подогревом", category: "Кузов", subcategory: "Зеркала", make: "", model: "", keywords: "зеркало" },
  { id: "k10", name: "Моторчик складывания зеркала, корпус зеркала", category: "Кузов", subcategory: "Зеркала", make: "", model: "", keywords: "зеркало моторчик" },
  { id: "k11", name: "Решетка радиатора, решетка бампера; молдинги; спойлер; дефлектор", category: "Кузов", subcategory: "Решетки и молдинги", make: "", model: "", keywords: "решетка молдинг спойлер" },
  // 8. Салон и интерьер
  { id: "s01", name: "Сиденье переднее (водительское, пассажирское)", category: "Салон", subcategory: "Сиденья", make: "", model: "", keywords: "сиденье кресло" },
  { id: "s02", name: "Сиденье заднее (диван, раздельные)", category: "Салон", subcategory: "Сиденья", make: "", model: "", keywords: "сиденье заднее" },
  { id: "s03", name: "Спортивное сиденье (Recaro, Bride); механизм, мотор, подогрев", category: "Салон", subcategory: "Сиденья", make: "", model: "", keywords: "recaro bride подогрев" },
  { id: "s04", name: "Панель приборов (торпедо), центральная консоль, бардачок", category: "Салон", subcategory: "Панели", make: "", model: "", keywords: "торпедо консоль бардачок" },
  { id: "s05", name: "Обшивка двери, стойки; потолок салона", category: "Салон", subcategory: "Панели", make: "", model: "", keywords: "обшивка потолок" },
  { id: "s06", name: "Комбинация приборов (спидометр), магнитола, навигация, дисплей", category: "Салон", subcategory: "Приборы и мультимедиа", make: "", model: "", keywords: "приборы магнитола навигация" },
  { id: "s07", name: "Блок управления климатом, прикуриватель, USB", category: "Салон", subcategory: "Приборы и мультимедиа", make: "", model: "", keywords: "климат прикуриватель" },
  { id: "s08", name: "Подушка безопасности (водитель, пассажир, боковая)", category: "Салон", subcategory: "Безопасность", make: "", model: "", keywords: "подушка безопасности airbag" },
  { id: "s09", name: "Ремень безопасности, преднатяжитель; датчик удара", category: "Салон", subcategory: "Безопасность", make: "", model: "", keywords: "ремень преднатяжитель" },
  { id: "s10", name: "Ковры салона, обивка потолка, обшивка багажника, шумоизоляция", category: "Салон", subcategory: "Обивка", make: "", model: "", keywords: "ковры обивка шумоизоляция" },
  // 9. Климат и кондиционирование
  { id: "c01", name: "Компрессор кондиционера (Denso, Sanden)", category: "Климат", subcategory: "Компрессор", make: "", model: "", keywords: "компрессор кондиционер denso sanden" },
  { id: "c02", name: "Муфта компрессора, шкив компрессора", category: "Климат", subcategory: "Компрессор", make: "", model: "", keywords: "муфта компрессор" },
  { id: "c03", name: "Радиатор кондиционера (конденсатор), испаритель, ресивер-осушитель", category: "Климат", subcategory: "Радиаторы", make: "", model: "", keywords: "конденсатор испаритель" },
  { id: "c04", name: "Трубки и патрубки кондиционера", category: "Климат", subcategory: "Радиаторы", make: "", model: "", keywords: "патрубок кондиционер" },
  { id: "c05", name: "Радиатор отопителя (печка), мотор отопителя", category: "Климат", subcategory: "Печка", make: "", model: "", keywords: "печка радиатор отопитель" },
  { id: "c06", name: "Дефлектор обдува, заслонка вентиляции", category: "Климат", subcategory: "Печка", make: "", model: "", keywords: "дефлектор заслонка" },
  // 10. Система питания
  { id: "f01", name: "Топливный насос (бензонасос)", category: "Топливная", subcategory: "Топливная система", make: "", model: "", keywords: "бензонасос топливный насос" },
  { id: "f02", name: "Топливный бак, форсунка, топливная рампа", category: "Топливная", subcategory: "Топливная система", make: "", model: "", keywords: "бак форсунка рампа" },
  { id: "f03", name: "Регулятор давления топлива, фильтр, магистраль; датчик уровня", category: "Топливная", subcategory: "Топливная система", make: "", model: "", keywords: "регулятор топливо фильтр" },
  { id: "f04", name: "Дроссельная заслонка, датчик положения дросселя, клапан ХХ", category: "Топливная", subcategory: "Дроссель и впуск", make: "", model: "", keywords: "дроссель клапан холостого" },
  // 11. Специализированные узлы
  { id: "x01", name: "Дифференциал передний, задний", category: "Трансмиссия", subcategory: "Дифференциал", make: "", model: "", keywords: "дифференциал" },
  { id: "x02", name: "Дифференциал LSD (самоблокирующийся), полуоси, сателлиты", category: "Трансмиссия", subcategory: "Дифференциал", make: "", model: "", keywords: "lsd дифференциал полуось" },
  { id: "x03", name: "Редуктор заднего моста, переднего моста", category: "Трансмиссия", subcategory: "Редукторы", make: "", model: "", keywords: "редуктор мост" },
  { id: "x04", name: "Мост в сборе (внедорожник)", category: "Трансмиссия", subcategory: "Редукторы", make: "", model: "", keywords: "мост внедорожник" },
  { id: "x05", name: "Гибрид: высоковольтная батарея, инвертор, электромотор", category: "Электрика/ЭБУ", subcategory: "Гибрид", make: "", model: "", keywords: "гибрид батарея инвертор" },
  { id: "x06", name: "Гибридная трансмиссия, DC-DC конвертор, блок управления гибридом", category: "Электрика/ЭБУ", subcategory: "Гибрид", make: "", model: "", keywords: "гибрид трансмиссия" },
  // 12. Аксессуары
  { id: "a01", name: "Магнитола штатная, усилитель, сабвуфер, динамики, антенна", category: "Автоаксессуары/расходники", subcategory: "Аудио", make: "", model: "", keywords: "магнитола усилитель динамики" },
  { id: "a02", name: "Камера заднего вида, парктроник, дисплей парковки", category: "Автоаксессуары/расходники", subcategory: "Парковка", make: "", model: "", keywords: "камера парктроник" },
  { id: "a03", name: "Плафон салона, подсветка багажника и ног, подсветка дверей", category: "Автоаксессуары/расходники", subcategory: "Освещение салона", make: "", model: "", keywords: "плафон подсветка" },
  { id: "a04", name: "Щетка стеклоочистителя (дворник)", category: "Автоаксессуары/расходники", subcategory: "Расходники", make: "", model: "", keywords: "дворник щетка стекло" },
];
